# Random Generators with Numpy

se usa el sub-paquete `random` del modulo `numpy`

In [1]:
import numpy as np
print('un numero pseudo aleatorio entre 0 y 1 - semilla elegida por python al llamar a rand')
np.random.rand()

un numero pseudo aleatorio entre 0 y 1 - semilla elegida por python al llamar a rand


0.5436131547471025

se puede elegir un numero entero como semilla con `np.random.seed(#int_semiila)` lo cual garantiza la Reproductibilidad, lo que significa que cualquiera que use la misma se milla puede replicar la serie de numeros aleatorios usados en un programa o simulación (respetando el numero  y orden de llamdos a rand() o randint())

In [2]:
np.random.seed(21)
print('primer numero en la serie:', np.random.rand())
print('segundo numero en la serie:', np.random.rand())

print('reset de la semilla al mismo valor')
np.random.seed(21)
print('primer numero en la serie:', np.random.rand())
print('segundo numero en la serie:', np.random.rand())



primer numero en la serie: 0.04872488080912729
segundo numero en la serie: 0.28910965978981684
reset de la semilla al mismo valor
primer numero en la serie: 0.04872488080912729
segundo numero en la serie: 0.28910965978981684


# Flip a Coin simulator

generar valores enteros entre un rango especifico: `[ inicio , fin+1 )`

In [3]:
coin = np.random.randint(0,2) # valores enteros entre 0 y 1
print(coin)
if coin == 0:
    print('Cara')
else:
    print('Sello')


0
Cara


# Arreglos o matrices Numpy de numeros aleatorios flotantes

si le pasan parametros a la funcion `np.random.rand()` estos seran entendidos como las dimenciones y numero de elemetos de un arreglo unidimencioal o una matriz multidimencional

In [4]:
# areglo de 5 numeros pseudo aleatorios entre 0 y 1
np.random.rand(5)

array([0.03614768, 0.95159898, 0.69767299, 0.15681427, 0.84618779])

In [5]:
# matriz 2x2 de numeros pseudo aleatorios entre 0 y 1
np.random.rand(2,2)

array([[0.34033785, 0.82435246],
       [0.17468076, 0.46289438]])

# Arreglos y Matrices de numeros enteros aleatorios

In [6]:
# run this to see randint documentation
#help(np.random.randint)

para crear un arreglo de N numeros aleatorios enteros se usa el siguiente formato `np.random.randint(min, max+1, N)`

In [7]:
min = 0
max  = 1
N = 5
print(f'arreglo de {N} numeros enteros entre {min} y {max}')

np.random.randint(min,max+1,N)

arreglo de 5 numeros enteros entre 0 y 1


array([0, 0, 0, 0, 0])

Para crear arreglos de N numeros enteros aleatorios en los que cada elementos tiene un min y maximo especifico se usa el siguiente formato:

    np.random.randint([min1, min2, ... , minN], [max1 + 1, max2 +1, ... , maxN + 1 ])

In [8]:
print('primer valor entre 0 y 1')
print('segundo valor entre 1 y 2')
print('primer valor entre 2 y 3')

np.random.randint([0,1,2],[1 +1,2 +1,3 +1])

primer valor entre 0 y 1
segundo valor entre 1 y 2
primer valor entre 2 y 3


array([1, 1, 3])

Para crear una matriz de N filas X M columnas en las que cada elemento esta entre min_global y max_gloval se usa el siguiente formato

`np.random.randint([[min_global]*M]*N,[max_global+1])`

In [9]:
min_global = 0
max_global = 2
filas = 2
columnas = 3
print(f'matriz {filas} X {columnas} con valores entre {min_global} y {max_global}')

np.random.randint([[min_global]*columnas]*filas,[max_global+1])

matriz 2 X 3 con valores entre 0 y 2


array([[0, 0, 1],
       [1, 2, 1]])

Para crear una matriz de N filas X M columnas en las que cada elemento esta entre min_col y max_col se usa el siguiente formato

`np.random.randint( [[min_col0, min_col1, ... ,min_colM]]*N, [max_col0 +1, max.col1 + 1, ... , max_colM +1 ] )`

In [10]:
# matriz 3x3 em la que los valores de la columna i estan entre i y i + 1 
print('min    ',0,'',1,'',2)
print('max    ',1,'',2,'',3)

np.random.randint( [[0,1,2]]*4, [1+1,2+1,3+1])

min     0  1  2
max     1  2  3


array([[0, 1, 2],
       [0, 1, 2],
       [0, 2, 3],
       [0, 1, 3]])

Para crear una matriz de N filas X M columnas en las que cada elemento esta entre min_row y max_row se usa el siguiente formato

`np.random.randint([[min_row0]*M,[min_row1]*M, ..., [min_rowN]*M], [[max_row0 + 1],[max_row1 + 1], ... , [max_rowN +1]])`

In [11]:
np.random.randint([[0]*2,[1]*2,[2]*2], [[2],[3],[4]])

array([[0, 0],
       [2, 2],
       [2, 2]])

Para crear una matriz de N filas X M columnas en las que cada elemento esta entre min_ij y max_ij se usa el siguiente formato

`np.random.randint([[min_11, min12, ... , min1M], [min_21, min22, ... , min2M], ... , [minN1, minN2, ... minNM]],`
                   
`               [[max_11 +1, max12+1, ... , max1M+1], [max_21+1, max22+1, ... , max2M+1], ... , [maxN1+1, maxN2+1, ... maxNM+1]])`


In [12]:
print(' 0 <= M[0][0] < 1' )
print(' 1 <= M[0][1] < 2' )
print(' 2 <= M[1][0] < 3' )
print(' 3 <= M[1][1] < 4' )
np.random.randint([[0,1],[2,3]], [[2,3],[4,5]])

 0 <= M[0][0] < 1
 1 <= M[0][1] < 2
 2 <= M[1][0] < 3
 3 <= M[1][1] < 4


array([[0, 2],
       [2, 3]])

# Random Walk